from tkinter import*
root=Tk()
root.title("Registration Form")
root.geometry("400x400")
root.configure(bg="light green")
root.resizable(False,False)
radio=StringVar()
def submit():
 file=open("myfile.txt",'w')
 info=file.write("Name: "+n1.get()+"\n"+"Email: "+n2.get()+"\n"+"MobileNo: "+n3.get()+"\n"+"Gender: "+radio.get()+"\n"+"city: "+Menu.get())
 print(info)
 file.close()

 
lbl=Label(root,text="registration form",font=("Arial 20 bold"))
lbl.place(x=100,y=20)
lbl1=Label(root,text="Name",font=("Arial 15"),fg="black")
lbl1.place(x=100,y=70)
n1=Entry(root,font=("Arial 15"))
n1.place(x=250,y=70)
lbl2=Label(root,text="Email",font=("Arial 15"),fg="black")
lbl2.place(x=100,y=120)
n2=Entry(root,font=("Arial 15"))
n2.place(x=255,y=120)
lbl3=Label(root,text="MobileNo",font=("Arial 15"),fg="black")
lbl3.place(x=100,y=180)
n3=Entry(root,font="Arial 15")
n3.place(x=330,y=180)
lbl4=Label(root,text="Gender",font=("Arial 15"),fg="black")
lbl4.place(x=100,y=230)
w=Radiobutton(root,text="male",variable=radio,value="male")
w.place(x=180,y=250)
w1=Radiobutton(root,text="female",variable=radio,value="female")
w1.place(x=250,y=250)
lbl5=Label(root,text="city",font=("Arial 15"),fg="black")
lbl5.place(x=100,y=300)
Menu=StringVar()
Menu.set("select city")
drop=OptionMenu(root,Menu,"Lucknow","Faizabad")
drop.place(x=150,y=300)
button=Button(root,text="submit",font=("Arial 15"),fg="black",command=submit)
button.place(x=250,y=350)

root.mainloop()